apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  creationTimestamp: null
  name: chartmuseum
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  rules:
  - host: chartmuseum.35.240.42.197.nip.io
    http:
      paths:
      - backend:
          serviceName: jenkins-x-chartmuseum
          servicePort: 8080
status:
  loadBalancer: {}
