# Source: jxboot-helmfile-resources/templates/buildpacks.yaml
apiVersion: jenkins.io/v1
kind: BuildPack
metadata:
  name: "kubernetes-workloads"
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  label: "Kubernetes Workloads: Automated CI+CD with GitOps Promotion"
  gitUrl: "https://github.com/jenkins-x-labs/jenkins-x-kubernetes.git"
  gitRef: "master"
