# Source: jxboot-helmfile-resources/templates/release-gpg-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-release-gpg
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: vault-infra
  data:
  - name: pubring.gpg
    key: secret/data/jenkins/release/gpg
    property: pubring.gpg
  - name: sec-jenkins.gpg
    key: secret/data/jenkins/release/gpg
    property: sec-jenkins.gpg
  - name: secring.gpg
    key: secret/data/jenkins/release/gpg
    property: secring.gpg
  - name: trustdb.gpg
    key: secret/data/jenkins/release/gpg
    property: trustdb.gpg
  template:
    type: Opaque
