apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        jstrachan:
          repos:
            jx3-demo1-dev:
              required_status_checks:
                contexts:
                - promotion-build
      protect-tested-repos: true
    deck:
      spyglass: {}
    gerrit: {}
    github:
      LinkURL: null
    owners_dir_blacklist:
      default: null
      repos: null
    plank: {}
    pod_namespace: jx
    postsubmits:
      jstrachan/jx3-demo1-dev:
      - agent: tekton
        branches:
        - master
        name: promotion
        skip_report: true
    presubmits:
      jstrachan/jx3-demo1-dev:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    sinker: {}
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: []
        skip-unknown-contexts: false
      merge_method:
        jstrachan/jx3-demo1-dev: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-demo1-dev
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-demo1-dev
      target_url: http://deck.cluster.local
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
