# Source: nexus/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: nexus
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: vault-infra
  data:
  - name: password
    key: secret/data/jx/adminUser
    property: password
  template:
    metadata:
      labels:
        app: nexus-nexus
        chart: "nexus-0.1.30"
        release: "nexus"
        heritage: "Helm"
    type: Opaque
