# Source: nexus/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    app: nexus
    chart: nexus-0.1.30
    release: nexus
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'environment'
  annotations:
    fabric8.io/expose: "true"
  namespace: jx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: nexus
  selector:
    app: nexus
    release: nexus
