# Source: chartmuseum/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-x-chartmuseum
  labels:
    app: jenkins-x-chartmuseum
    release: "chartmuseum"
    gitops.jenkins-x.io/pipeline: 'environment'
  namespace: jx
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
